In [10]:
import pygad
import numpy as np
import matplotlib.pyplot as plt
import torch
import pygad
import pygad.nn
import pygad.gann
import itertools

In [40]:
def calculate_xor(inputs):
    inputs = inputs.T
    L2 = []
    targets = []
    for i in range(0, len(inputs), 2):
        L2.append((inputs[i], inputs[i+1]))

    for i in range(len(L2)):
        targets.append(L2[i][0] ^ L2[i][1])

    return np.array(targets).T

In [ ]:
def fitness_func(solution, sol_idx):
    global GANN_instance, data_inputs, data_outputs

    predictions = pygad.nn.predict(last_layer=GANN_instance.population_networks[sol_idx],
                                   data_inputs=data_inputs)
    correct_predictions = np.where(predictions == data_outputs)[0].size

    print(predictions, correct_predictions)


    solution_fitness = (correct_predictions/data_outputs.size)*100
    return solution_fitness

def callback_generation(ga_instance):
    global GANN_instance

    population_matrices = pygad.gann.population_as_matrices(population_networks=GANN_instance.population_networks, 
                                                            population_vectors=ga_instance.population)
    GANN_instance.update_population_trained_weights(population_trained_weights=population_matrices)

    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    print("Accuracy   = {fitness}".format(fitness=ga_instance.best_solution()[1]))
data_inputs = np.array([[1, 1],
                        [1, 0],
                        [0, 1],
                        [0, 0]])

data_outputs = np.array([0, 
                        1, 
                        1, 
                        0])

GANN_instance = pygad.gann.GANN(num_solutions=5,
                                num_neurons_input=2,
                                num_neurons_hidden_layers=[2],
                                num_neurons_output=2,
                                hidden_activations=["relu"],
                                output_activation="softmax")

population_vectors = pygad.gann.population_as_vectors(population_networks=GANN_instance.population_networks)
ga_instance = pygad.GA(num_generations=50, 
                       num_parents_mating=3, 
                       initial_population=population_vectors.copy(),
                       fitness_func=fitness_func,
                       mutation_percent_genes=5,
                       callback_generation=callback_generation)

# ga_instance.run()
# ga_instance.plot_result()

# solution, solution_fitness, solution_idx = ga_instance.best_solution()
# print(solution)
# print(solution_fitness)
# print(solution_idx)

In [109]:
print(data_inputs.shape, data_outputs.shape)

(4, 2) (4,)


In [110]:
four_xor_gates = []
for x in itertools.product([1,0],repeat=4):
    four_xor_gates.append(np.array(x))

four_xor_gates = np.array(four_xor_gates)

In [118]:
print(four_xor_gates[1])

[1 1 1 0]


In [119]:
solutions = calculate_xor(four_xor_gates)
print(solutions[1])

[0 1]


In [101]:
print(solutions)

[[0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0]]


In [104]:
def fitness_func(solution, sol_idx):
    global GANN_instance, data_inputs, data_outputs

    predictions = pygad.nn.predict(last_layer=GANN_instance.population_networks[sol_idx],
                                   data_inputs=data_inputs)
    correct_predictions = np.where(predictions == data_outputs)[0].size

    print(predictions, correct_predictions)
    
    solution_fitness = (correct_predictions/data_outputs.size)*100
    return solution_fitness







    

def callback_generation(ga_instance):
    global GANN_instance

    population_matrices = pygad.gann.population_as_matrices(population_networks=GANN_instance.population_networks, 
                                                            population_vectors=ga_instance.population)
    GANN_instance.update_population_trained_weights(population_trained_weights=population_matrices)

    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    print("Accuracy   = {fitness}".format(fitness=ga_instance.best_solution()[1]))
data_inputs = four_xor_gates

data_outputs = solutions

GANN_instance = pygad.gann.GANN(num_solutions=100,
                                num_neurons_input=4,
                                num_neurons_hidden_layers=[4],
                                num_neurons_output=2,
                                hidden_activations=["relu"],
                                output_activation="softmax")

population_vectors = pygad.gann.population_as_vectors(population_networks=GANN_instance.population_networks)
ga_instance = pygad.GA(num_generations=5, 
                       num_parents_mating=3, 
                       initial_population=population_vectors.copy(),
                       fitness_func=fitness_func,
                       mutation_percent_genes=5,
                       callback_generation=callback_generation)


ga_instance.run()
ga_instance.plot_result()

/Users/luca/.pyenv/versions/AI_Lab/lib/python3.10/site-packages/pygad/pygad.py:764: UserWarning: Starting from PyGAD 2.6.0, the callback_generation parameter is deprecated and will be removed in a later release of PyGAD. Please use the on_generation parameter instead.
  if not self.suppress_warnings: warnings.warn("Starting from PyGAD 2.6.0, the callback_generation parameter is deprecated and will be removed in a later release of PyGAD. Please use the on_generation parameter instead.")


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 16)

In [63]:
predictions = pygad.nn.predict(last_layer=GANN_instance.population_networks[3],
                                   data_inputs=data_inputs)

In [64]:
predictions

[0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0]

In [65]:
correct_predictions = np.where(predictions == data_outputs)[0].size

/var/folders/r9/9kmctj5907z_qfw6hp7s7bb40000gn/T/ipykernel_90427/2534927365.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  correct_predictions = np.where(predictions == data_outputs)[0].size


In [66]:
correct_predictions

0

array([0, 0])

In [69]:
predictions == data_outputs

/var/folders/r9/9kmctj5907z_qfw6hp7s7bb40000gn/T/ipykernel_90427/4252064015.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  predictions == data_outputs


False